
name: Fuzzing Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  fuzz:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: "Set up Docker-Compose"
      uses: hoverkraft-tech/compose-action@v2.0.1

    - name: Download SecList 
      run: |
        wget -c https://github.com/danielmiessler/SecLists/archive/master.zip -O SecList.zip \
        && unzip SecList.zip \
        && rm -f SecList.zip

    - name: Install FFUF
      run: | 
        go install github.com/ffuf/ffuf/v2@latest

    - name: Scan with FFUF
      run: | 
        ~/go/bin/ffuf -w SecLists-master/Discovery/Web-Content/directory-list-1.0.txt -u http://localhost:8888/FUZZ
